name: Deploy Staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy a Staging via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP_DEL_SERVIDOR }}
          username: ${{ secrets.USUARIO_SERVIDOR }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/lemp-sites/ale_quiroga/staging/devops_ci-cd
            git fetch origin
            git reset --hard origin/develop
